Comments; ColorSensor; Nothing to do with vision tracking
ASL-Robotics/RobotCode2020 pull request #63
Opened 2020-02-01 11:18 UTC by p-casals

2020-02-01 12:19 UTC, p-casals commented
Got rid of all the pixypacket stuff; I'm not going to do that. ColorSensor works now and the comments are done

2020-02-01 14:29 UTC, p-casals commented
intake buttons streamlined; they now make more sense. coloursensor can now take data automatically

2020-02-01 14:48 UTC, LordSquishers requested changes

2020-02-01 14:48 UTC, LordSquishers commented on src/main/java/frc/robot/commands/auto/routines/TestAutoCommandGroup.java
> +
heheh fix

2020-02-01 14:48 UTC, LordSquishers commented on src/main/java/frc/robot/subsystems/ColorSensor.java
> +    for(int i = 0; i < 4; i++) {
rethink

2020-02-01 14:48 UTC, LordSquishers commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +
no

2020-02-01 14:51 UTC, p-casals commented
alright done

2020-02-03 15:16 UTC, LordSquishers approved these changes
commenting out broken code does not fix it- please make sure this is functional

2020-02-03 15:16 UTC, merged